### ISSUE TITLE
Maintaining parent context

### ISSUE THREAD

**Issue by andru** [jquense/react-layer#1]
I'm having difficulties finding a way to make the parent context match the owner context.

I'm wrapping Layer in a higher order component more or less the same as `createLayeredComponent` in the readme.

Perhaps I'm misunderstanding how React constructs it's parent tree here; I thought the higher order component would be sufficient but I'm getting warnings about the parent and owner context's being different. All `parent` context properties are `undefined`.

I'm exporting my Modal component wrapped by createLayeredComponent...

```
export default createLayeredComponent(function(props) {
  return (
    <UnwrappedModal {...props}>
      {props.children}
    </UnwrappedModal>
  )
})
```

and then creating component instances...

```
//Modal is the component exported above
<Modal isOpen={...} >
   <SomeComponentWhichNeedsParentContext />
</Modal>
```

Am I misunderstanding something? Any tips?

**Comment by jquense** [comment]
so right now this is sort of an unsolved issue with parent contexts. In a recent commit in React they added a utility specifically to handle the case of passing parent context to the children rendered into a different subtree (like here). Unfortunately  I don't think there is much I can do to handle it until `0.14.0` is released and parent contexts are properly supported

**Comment by andru** [comment]
Right, I've seen mention of that elsewhere but I don't know enough about React internals yet to really say I grasp the finer details.

I thought that it was the mismatch between owner and parent context which was causing a bug in my app, but it actually turned out to be something else.  The context is accessible via the owner right now, and things work as expected, just with some warnings.

Is it safe to just ignore the warnings until `0.14.0` provides a solution, or does this imply I need to rethink my structure? Are there any issues you know of? 

Thanks for your help and the sweet component!

**Comment by jquense** [comment]
Glad to help, The warning is generally safe to ignore everyone but probably especially so in the case of layer context mismatches, which are resulting from the parent context not making the "jump" to the new subtree the layer renders (whereas the owner based ones do). There shouldn't really be any case where something that works as an owner based context will fail in the new parent based ones (b/c they are a subset of parent contexts)
